apiVersion: v1
kind: Pod
metadata:
  name: log-sender
spec:
  containers:
  - image: gcr.io/apmap-146422/log_sender/log_sender
    name: log-sender
    volumeMounts:
    - mountPath: /d
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      path: /var/lib/docker
